[build]
  command = "npm install && ./node_modules/.bin/ng build --configuration production"
  publish = "dist/chambre-froide/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
